#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. tools/RunFunctions

{{#usePotentialFoam}}
{{#eachCaseParallel}}
runParallel -o potentialFoam
{{/eachCaseParallel}}
{{^eachCaseParallel}}
runApplication -o potentialFoam
{{/eachCaseParallel}}
{{/usePotentialFoam}}

{{#eachCaseParallel}}
runParallel -o simpleFoam
{{/eachCaseParallel}}
{{^eachCaseParallel}}
runApplication -o simpleFoam
{{/eachCaseParallel}}

{{#runSample}}
{{#eachCaseParallel}}
runParallel  -o postProcess -latestTime -func sampleDict
{{/eachCaseParallel}}
{{^eachCaseParallel}}
runApplication -o postProcess -latestTime -func sampleDict
{{/eachCaseParallel}}
{{/runSample}}